id: I6E644426
ocr_import_info:
  timestamp: '2023-09-28T04:49:42.933278+00:00'
  batch_id: batch-49e5
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 08:14:18.581022+00:00
last_modified: 2023-09-28 08:14:18.581028+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM2902
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM2902
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱས་པའི་བསྟན་བཅོས་ཚད་མ་རྣམ་འགྲེལ་གྱི་ལེའུ་གཉིས་པའི་མཐའ་དཔྱོད་མཁས་པའི་དབང་པོ་རྗེ་རྟ་ནག་པ་དགེ་འདུན་བློ་བཟང་གི་གསུང་རྒྱུན་དྲི་མ་མེད་པ་སོགས།
  languages:
  - bo
  author: རྟ་ནག་པ་དགེ་འདུན་བློ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.9696913841708402
  ocr_word_median_confidence_index: 0.99949694
bases:
  I1NLM2902_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM2902_001
      total_pages: 238
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM2902_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.99949694
      ocr_word_mean_confidence_index: 0.9696913841708402
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
